##headless service
apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  selector:
    dns: test
  clusterIP: None

---
## deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dns
  labels:
    dns: test
spec:
  replicas: 3
  selector:
    matchLabels:
      dns: test
  template:
    metadata:
      labels:
        dns: test
    spec:
      hostname: hello-dns
      subdomain: headless-service
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        -  containerPort: 80