##headless service
apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  selector:
    dns: test
  clusterIP: None
  ports:
  -  name: http
     port: 80
     targetPort: 80

---
## deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dns
  labels:
    dns: test
spec:
  replicas: 1
  selector:
    matchLabels:
      dns: test
  template:
    metadata:
      labels:
        dns: test
    spec:
      subdomain: headless-service
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        -  containerPort: 80
