apiVersion: v1
kind: Pod
metadata:
  name: config-map-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","cat /etc/config/stuff" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-conf-map
        items:
        - key: disk.type
          path: stuff
  restartPolicy: Never