apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      scale: deploy
  template:
    metadata:
      labels:
        scale: deploy
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
